//
// Created by JensenJiang on 2017/6/27.
//

#ifndef PARALLEL_DAG_TRAVERSAL_PARAMETERS_H
#define PARALLEL_DAG_TRAVERSAL_PARAMETERS_H
#define MINCOST -1
#define MAX_OUTPUT_BUFFER_SIZE 5000
#define MAX_CUR 12

#endif //PARALLEL_DAG_TRAVERSAL_PARAMETERS_H
